pipeline:
  build-push:
    group: docker
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      registry: ghcr.io
      repo: ghcr.io/synost/streato-accounts
      dockerfile: Dockerfile
      platforms: linux/amd64
      # remove 'latest' on older version branches to avoid accidental downgrade
      tag: [latest, "${CI_COMMIT_TAG}"]
    when:
      event: tag
